<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Users_model extends CI_Model
{
	public $table = "users";

	public function __construct()
	{
		parent::__construct();
	}

	public function listaEstados() {
		return $this->db->query(" SELECT id, nome, sigla, status 
								  FROM estados
								  ORDER BY nome ASC")
						->result();
	}

	 public function ListaCidadesPorEstados($estados_id) {
		return $this->db->query(" SELECT id, nome, estados_id
								  FROM cidades
								  WHERE estados_id = '$estados_id'
								  ORDER BY capital DESC, nome ASC")
						->result();	
	}
	
}
